package com.getronics.ficherodiario.util;

import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HojaUnoExcel {
	
	static Date date = new Date();
	static SimpleDateFormat formato = new SimpleDateFormat("yyyy_MM_dd");
	static String fechaActual = formato.format(date);
	
	private static final String EXCEL_FILE_PATH="C:/Log/fichero_" + fechaActual +".xlsx";

	private Logger logHojaUno = LoggerFactory.getLogger(this.getClass());
	
	public void crearHojaExcel(List<String> tipoIdentificador,List<String> tipoMovimiento, List<String> protegidoTipAseguramientoAndTipMovimiento,
			List<String> registroIpfNulo,List<String> informeAltaCruzado,List<String> codTipoAsegurado,List<String> titDobleCobertura,List<String> beneDobleCobertura) {

		/*"COD_TIPO_ASEGURADO","TIPO_MOVIMIENTO","IPF","DNI_NIE","PASAPORTE","NAF","NAF_SEC1","NAF_SEC2","NAF_SEC3","NAF_SEC4",
				"NAF_SEC5","NAF_SEC6","NAF_SEC7","NAF_SEC8","NAF_SEC9","INDICATIVO_NOMBRE","APELLIDOS_NOMBRE","APELLIDO1","APELLIDO2",
				"NOMBRE	NACIONALIDAD","FECHA_NACIMIENTO","SEXO","INDICATIVO_DOMICILIO","DOMICILIO","TIPO_ASEGURAMIENTO",
				"COD_INDICADOR_DE_FARMACIA","COD_SUBINDICADOR_DE_FARMACIA","COD_SITUACION","FECHA_EFECTO_SITUACION","COD_TIPO_BENEFICIARIO",
				"IPF_TITULAR","NAF_TITULAR","NUMERO_SECUENCIA","FECHA_NACIMIENTO_RAW","IPF_ANTERIOR","COD_USUARIO_SNS","CODIGO_BADAS",
				"MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA","CIP_MUTUALISTA","CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL",
				"PRESTADORA_PRIVADA" */
		
		final String[] header= {"TIPO","TOTAL_","COD_TIPO_ASEGURADO_","TIPO_MOVIMIENTO_,","COD_SITUACION_","TOTAL_","COD_TIPO_ASEGURADO_","TIPO_MOVIMIENTO_	","PROTEGIDA","TOTAL_","COD_TIPO_ASEGURADO_","TIPO_MOVIMIENTO_",	
				"COD_SITUACION_","NUMERO_","TIPO_ASEGURAMIENTO_","TIPO_MOVIMIENTO_","TOTAL_","COD_TIPO_ASEGURADO_","TOTAL_","DOBLE_COBERTURA","TOTAL_",
				"DOBLE_COBERTURA_","TOTAL_","TIPO","TOTAL_","COD_TIPO_ASEGURADO_","TIPO_MOVIMIENTO_","COD_SITUACION_","TOTAL_","COD_TIPO_ASEGURADO_",
				"TIPO_MOVIMIENTO_","PROTEGIDA","TOTAL_","COD_TIPO_ASEGURADO_","TIPO_MOVIMIENTO_","COD_SITUACION_","NUMERO_","TIPO_ASEGURAMIENTO_","TIPO_MOVIMIENTO_","TOTAL_",
				"COD_TIPO_ASEGURADO_","TOTAL_","COD_TIPO_ASEGURADO_","MOTIVO_BAJA_","TOTAL_","TIPO_ASEGURAMIENTO_","NUMERO_","ENVIO_INSS","ESTADO EN EL SNS_","NUMERO_",	
				"COD_TIPO_ASEGURADO_","MOTIVO_BAJA_","TOTAL_","COD_ESTADO_","NUMERO_","INDICADOR_DE_FARMACIA_","SUBINDICADOR_","TOTAL_","TIPO_ASEGURAMIENTO_",	
				"INDICADOR_DE_FARMACIA_","SUBINDICADOR_","TOTAL_","COD_TIPO_ASEGURADO","TIPO_MOVIMIENTO","IPF","DNI_NIE","PASAPORTE","NAF","NAF_SEC1","NAF_SEC2",
				"NAF_SEC3","NAF_SEC4","NAF_SEC5","NAF_SEC6","NAF_SEC7","NAF_SEC8","NAF_SEC9","INDICATIVO_NOMBRE","APELLIDOS_NOMBRE","APELLIDO1","APELLIDO2",	
				"NOMBRE","NACIONALIDAD","FECHA_NACIMIENTO",	"SEXO",	"INDICATIVO_DOMICILIO","DOMICILIO",	"TIPO_ASEGURAMIENTO",	"COD_INDICADOR_DE_FARMACIA","COD_SUBINDICADOR_DE_FARMACIA",
				"COD_SITUACION",	"FECHA_EFECTO_SITUACION",	"COD_TIPO_BENEFICIARIO",	"IPF_TITULAR",	"NAF_TITULAR",	"NUMERO_SECUENCIA","FECHA_NACIMIENTO_RAW","IPF_ANTERIOR",
				"COD_USUARIO_SNS","CODIGO_BADAS","MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA",	"CIP_MUTUALISTA","CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL",
				"PRESTADORA_PRIVADA", "NAF","COD_TIPO_ASEGURADO","TIPO_MOVIMIENTO","IPF","DNI_NIE","PASAPORTE","NAF_1","NAF_SEC1",
				"NAF_SEC2",	"NAF_SEC3","NAF_SEC4","NAF_SEC5","NAF_SEC6","NAF_SEC7","NAF_SEC8","NAF_SEC9","INDICATIVO_NOMBRE","APELLIDOS_NOMBRE","APELLIDO1","APELLIDO2","NOMBRE",
				"NACIONALIDAD","FECHA_NACIMIENTO","SEXO","INDICATIVO_DOMICILIO","DOMICILIO","TIPO_ASEGURAMIENTO","COD_INDICADOR_DE_FARMACIA",
				"COD_SUBINDICADOR_DE_FARMACIA","COD_SITUACION","FECHA_EFECTO_SITUACION","COD_TIPO_BENEFICIARIO",
				"IPF_TITULAR","NAF_TITULAR","NUMERO_SECUENCIA","FECHA_NACIMIENTO_RAW","IPF_ANTERIOR","COD_USUARIO_SNS","CODIGO_BADAS",
				"MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA","CIP_MUTUALISTA","CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL",
				"PRESTADORA_PRIVADA","COD_TIPO_ASEGURADO","TIPO_MOVIMIENTO","IPF","DNI_NIE","PASAPORTE","NAF","NAF_SEC1","NAF_SEC2",
				"NAF_SEC3","NAF_SEC4","NAF_SEC5","NAF_SEC6","NAF_SEC7","NAF_SEC8","NAF_SEC9","INDICATIVO_NOMBRE",
				"APELLIDOS_NOMBRE","APELLIDO1","APELLIDO2","NOMBRE","NACIONALIDAD","FECHA_NACIMIENTO","SEXO","INDICATIVO_DOMICILIO",
				"DOMICILIO","TIPO_ASEGURAMIENTO","COD_INDICADOR_DE_FARMACIA","COD_SUBINDICADOR_DE_FARMACIA","COD_SITUACION",
				"FECHA_EFECTO_SITUACION","COD_TIPO_BENEFICIARIO","IPF_TITULAR","NAF_TITULAR","NUMERO_SECUENCIA","FECHA_NACIMIENTO_RAW",
				"IPF_ANTERIOR","COD_USUARIO_SNS","CODIGO_BADAS","MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA","CIP_MUTUALISTA",
				"CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL","PRESTADORA_PRIVADA","COD_TIPO_ASEGURADO","TIPO_MOVIMIENTO","IPF","DNI_NIE",
				"PASAPORTE","NAF","NAF_SEC1","NAF_SEC2","NAF_SEC3","NAF_SEC4","NAF_SEC5","NAF_SEC6","NAF_SEC7","NAF_SEC8",
				"NAF_SEC9","INDICATIVO_NOMBRE","APELLIDOS_NOMBRE","APELLIDO1","APELLIDO2","NOMBRE","NACIONALIDAD","FECHA_NACIMIENTO",
				"SEXO","INDICATIVO_DOMICILIO","DOMICILIO","TIPO_ASEGURAMIENTO","COD_INDICADOR_DE_FARMACIA","COD_SUBINDICADOR_DE_FARMACIA",
				"COD_SITUACION","FECHA_EFECTO_SITUACION","COD_TIPO_BENEFICIARIO","IPF_TITULAR","NAF_TITULAR","NUMERO_SECUENCIA",
				"FECHA_NACIMIENTO_RAW","IPF_ANTERIOR","COD_USUARIO_SNS","CODIGO_BADAS","MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA",
				"CIP_MUTUALISTA","CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL","PRESTADORA_PRIVADA","COD_TIPO_ASEGURADO",
				"TIPO_MOVIMIENTO","IPF","DNI_NIE","PASAPORTE","NAF","NAF_SEC1","NAF_SEC2","NAF_SEC3","NAF_SEC4","NAF_SEC5",
				"NAF_SEC6","NAF_SEC7","NAF_SEC8","NAF_SEC9","INDICATIVO_NOMBRE","APELLIDOS_NOMBRE","APELLIDO1","APELLIDO2",
				"NOMBRE","NACIONALIDAD","FECHA_NACIMIENTO","SEXO","INDICATIVO_DOMICILIO","DOMICILIO","TIPO_ASEGURAMIENTO",
				"COD_INDICADOR_DE_FARMACIA","COD_SUBINDICADOR_DE_FARMACIA","COD_SITUACION","FECHA_EFECTO_SITUACION","COD_TIPO_BENEFICIARIO",
				"IPF_TITULAR","NAF_TITULAR","NUMERO_SECUENCIA","FECHA_NACIMIENTO_RAW","IPF_ANTERIOR","COD_USUARIO_SNS","CODIGO_BADAS",
				"MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA","CIP_MUTUALISTA","CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL",
				"PRESTADORA_PRIVADA","COD_TIPO_ASEGURADO","TIPO_MOVIMIENTO","IPF","DNI_NIE","PASAPORTE","NAF","NAF_SEC1","NAF_SEC2","NAF_SEC3",
				"NAF_SEC4","NAF_SEC5","NAF_SEC6","NAF_SEC7","NAF_SEC8","NAF_SEC9","INDICATIVO_NOMBRE","APELLIDOS_NOMBRE","APELLIDO1",
				"APELLIDO2","NOMBRE","NACIONALIDAD","FECHA_NACIMIENTO","SEXO","INDICATIVO_DOMICILIO","DOMICILIO","TIPO_ASEGURAMIENTO",
				"COD_INDICADOR_DE_FARMACIA","COD_SUBINDICADOR_DE_FARMACIA","COD_SITUACION","FECHA_EFECTO_SITUACION","COD_TIPO_BENEFICIARIO",
				"IPF_TITULAR","NAF_TITULAR","NUMERO_SECUENCIA","FECHA_NACIMIENTO_RAW","IPF_ANTERIOR","COD_USUARIO_SNS","CODIGO_BADAS",
				"MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA","CIP_MUTUALISTA","CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL",
				"PRESTADORA_PRIVADA","DOBLE_COBERTURA","TOTAL_","DOBLE_COBERTURA_","TOTAL_","INDICADOR_CONVENIO_RURAL","TOTAL_","INDICADOR_CONVENIO_RURAL_",
				"TOTAL_","REGUPRIV_REGUPUB","REGUPRIV_IRREGUPUB","REGUPRIV_NOEXISTE","TOTAL_ESPERADO_REG","IRREGUPRIV_REGUPUB","IRREGUPRIV_IRREGUPUB",
				"IRREGUPRIV_NOEXISTE","TOTAL_ESPERADO_IRREG","COD_TIPO_ASEGURADO","TIPO_MOVIMIENTO","IPF","DNI_NIE","PASAPORTE","NAF","NAF_SEC1",
				"NAF_SEC2","NAF_SEC3","NAF_SEC4","NAF_SEC5","NAF_SEC6","NAF_SEC7","NAF_SEC8","NAF_SEC9","INDICATIVO_NOMBRE",
				"APELLIDOS_NOMBRE","APELLIDO1","APELLIDO2","NOMBRE","NACIONALIDAD","FECHA_NACIMIENTO","SEXO","INDICATIVO_DOMICILIO",
				"DOMICILIO","TIPO_ASEGURAMIENTO","COD_INDICADOR_DE_FARMACIA","COD_SUBINDICADOR_DE_FARMACIA","COD_SITUACION",
				"FECHA_EFECTO_SITUACION","COD_TIPO_BENEFICIARIO","IPF_TITULAR","NAF_TITULAR","NUMERO_SECUENCIA","FECHA_NACIMIENTO_RAW",
				"IPF_ANTERIOR","COD_USUARIO_SNS","CODIGO_BADAS","MOTIVO_BAJA","PROTEGIDA","INDICADOR_DOBLE_COBERTURA","CIP_MUTUALISTA",
				"CIP_MUTUALISTA_TITULAR","INDICADOR_CONVENIO_RURAL","PRESTADORA_PRIVADA","BAJAPRIV_BAJAPUB","BAJAPRIV_BAJANOEXISTE"};
		
		Workbook workbook  = new XSSFWorkbook();
		
		// SE INDICA EL NOMBRE DE LA PÁGINA DEL EXCEL

		
		Sheet sheet = workbook .createSheet("DATOS");
		
		Row row = sheet.createRow(0);
	    for(int i = 0; i < header.length; i++) {
	       // each column 20 characters wide
	       sheet.setColumnWidth(i, 20*256);
	       Cell cell = row.createCell(i);
	       cell.setCellValue(header[i]);
	      // cell.setCellStyle(style);
	    } 
		
	    int rowNum = 1;
	    
	    // Separamos el String que entra para crear las filas. 
	    
	    
	    for(String a: tipoIdentificador) {
	    	String [] separar = a.split(",");
	    	row = sheet.createRow(rowNum++);
	        row.createCell(0).setCellValue(separar[0]);
	        row.createCell(1).setCellValue(separar[1]);
	    }
	    
		for (String a : tipoMovimiento) {
			String[] separar = a.split(",");
			row = sheet.createRow(rowNum++);
			if (separar[0]=="null") {
				separar[0] = "";
			} else {
				row.createCell(2).setCellValue(separar[0]);
			}
			if (separar[1]=="null") {
				separar[1] = "";
			} else {
				row.createCell(3).setCellValue(separar[1]);
			}
			if (separar[2]=="null") {
				separar[2] = "";
			} else {
				row.createCell(4).setCellValue(separar[2]);
			}
			if (separar[3]=="null") {
				separar[3] = "";
			} else {
				row.createCell(5).setCellValue(separar[3]);
			}
		}
	    
		
	    FileOutputStream outputStream = null;

		try {
			outputStream = new FileOutputStream(EXCEL_FILE_PATH);
			workbook.write(outputStream);
		} catch (IOException e) {
			logHojaUno.error(e.getMessage(), e);
		} finally {
			if (outputStream != null) {
				try {
					outputStream.close();
					workbook.close();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					logHojaUno.error(e.getMessage(), e);
				}
			}
		}

	}

}
